## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#343b43", bg = "#ffffff" }
"dimmed"    = { fg = "#88929d", bg = "#ffffff" }
"title"     = { fg = "#622cbc", bold = true }
"shortcut"  = { fg = "#a0111f" }
"matched"   = { fg = "#956400" }
"border"    = { fg = "#88929d" }
"selected"  = { bg = "#e7ecf0", fg = "#343b43", bold = true }

"source_marker" = { bg = "#024c1a", fg = "#ffffff", bold = true }
"target_marker" = { bg = "#032563", fg = "#ffffff", bold = true }

"status" = { bg = "#e7ecf0" }
"status title" = { fg = "#ffffff", bg = "#622cbc", bold = true }

"revset title" = { fg = "#622cbc", bg = "#e7ecf0", bold = true }
"revset text" = { fg = "#343b43", bold = true }
"revset completion text" = { fg = "#343b43" }
"revset completion matched" = { fg = "#956400", bold = true }
"revset completion dimmed" = { fg = "#88929d" }
"revset completion selected" = { bg = "#20252c", fg = "#acb6c0" }

"revisions" = { fg = "#343b43" }
"revisions selected" = { bg = "#acb6c0"}
"revisions dimmed" = { fg = "#88929d" }
"revisions details selected" = { bg = "#66707b" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#343b43" }
"evolog selected" = { bg = "#20252c", fg = "#e7ecf0", bold = true }

"menu" = { bg = "#ffffff" }
"menu title" = { fg = "#ffffff", bg = "#a0111f", bold = true }
"menu shortcut" = { fg = "#a0111f" }
"menu matched" = { fg = "#956400", bold = true }
"menu dimmed" = { fg = "#88929d" }
"menu border" = { fg = "#e7ecf0" }
"menu selected" = { bg = "#20252c", fg = "#e7ecf0" }

"help" = { bg = "#ffffff" }
"help title" = { fg = "#032563", bold = true, underline = true }
"help border" = { fg = "#e7ecf0" }

"preview" = { fg = "#343b43" }
"preview border" = { fg = "#e7ecf0" }

"confirmation" = { bg = "#ffffff" }
"confirmation text" = { fg = "#622cbc", bold = true }
"confirmation dimmed" = { fg = "#88929d" }
"confirmation border" = { fg = "#702c00", bold = true }
"confirmation selected" = { bg = "#20252c", fg = "#e7ecf0" }

"undo" = { bg = "#ffffff" }
"undo confirmation dimmed" = { fg = "#88929d" }
"undo confirmation selected" = { bg = "#20252c", fg = "#e7ecf0" }

"success" = { fg = "#032563", bold = true }
"error" = { fg = "#702c00", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#a0111f" }
"status dimmed" = { fg = "#88929d" }

"details" = { fg = "#343b43" }
"details selected" = { bold = true }
"completion" = { fg = "#343b43" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#622cbc" }
"branch" = { fg = "#023b95" }
"commit" = { fg = "#032563" }
"file" = { fg = "#956400" }
"change" = { fg = "#702c00" }
"bookmark" = { fg = "#a0111f" }


