## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Neovim Dark
# Scheme author: https://github.com/neovim/neovim/blob/master/src/nvim/highlight_group.c
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#e0e2ea", bg = "#14161b" }
"dimmed"    = { fg = "#9b9ea4", bg = "#14161b" }
"title"     = { fg = "#a6dbff", bold = true }
"shortcut"  = { fg = "#ffcaff" }
"matched"   = { fg = "#fce094" }
"border"    = { fg = "#9b9ea4" }
"selected"  = { bg = "#07080d", fg = "#e0e2ea", bold = true }

"source_marker" = { bg = "#8cf8f7", fg = "#14161b", bold = true }
"target_marker" = { bg = "#b3f6c0", fg = "#14161b", bold = true }

"status" = { bg = "#07080d" }
"status title" = { fg = "#14161b", bg = "#a6dbff", bold = true }

"revset title" = { fg = "#a6dbff", bold = true }
"revset text" = { fg = "#e0e2ea", bold = true }
"revset completion text" = { fg = "#e0e2ea" }
"revset completion matched" = { fg = "#fce094", bold = true }
"revset completion dimmed" = { fg = "#9b9ea4" }
"revset completion selected" = { bg = "#4f5258", fg = "#e0e2ea" }

"revisions" = { fg = "#e0e2ea" }
"revisions selected" = { bg = "#07080d"}
"revisions dimmed" = { fg = "#9b9ea4" }
"revisions details selected" = { bg = "#4f5258" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#e0e2ea" }
"evolog selected" = { bg = "#4f5258", fg = "#e0e2ea", bold = true }

"menu" = { bg = "#14161b" }
"menu title" = { fg = "#14161b", bg = "#ffcaff", bold = true }
"menu shortcut" = { fg = "#ffcaff" }
"menu matched" = { fg = "#fce094", bold = true }
"menu dimmed" = { fg = "#9b9ea4" }
"menu border" = { fg = "#07080d" }
"menu selected" = { bg = "#4f5258", fg = "#e0e2ea" }

"help" = { bg = "#14161b" }
"help title" = { fg = "#b3f6c0", bold = true, underline = true }
"help border" = { fg = "#07080d" }

"preview" = { fg = "#e0e2ea" }
"preview border" = { fg = "#07080d" }

"confirmation" = { bg = "#14161b" }
"confirmation text" = { fg = "#a6dbff", bold = true }
"confirmation dimmed" = { fg = "#9b9ea4" }
"confirmation border" = { fg = "#ffc0b9", bold = true }
"confirmation selected" = { bg = "#4f5258", fg = "#e0e2ea" }

"undo" = { bg = "#14161b" }
"undo confirmation dimmed" = { fg = "#9b9ea4" }
"undo confirmation selected" = { bg = "#4f5258", fg = "#e0e2ea" }

"success" = { fg = "#b3f6c0", bold = true }
"error" = { fg = "#ffc0b9", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#ffcaff" }
"status dimmed" = { fg = "#9b9ea4" }

"details" = { fg = "#e0e2ea" }
"details selected" = { bold = true }
"completion" = { fg = "#e0e2ea" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#a6dbff" }
"branch" = { fg = "#ffa500" }
"commit" = { fg = "#b3f6c0" }
"file" = { fg = "#fce094" }
"change" = { fg = "#ffc0b9" }
"bookmark" = { fg = "#ffcaff" }


