## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Github Dark Dimmed
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#d1d7e0", bg = "#0d1117" }
"dimmed"    = { fg = "#656c76", bg = "#0d1117" }
"title"     = { fg = "#539bf5", bold = true }
"shortcut"  = { fg = "#b083f0" }
"matched"   = { fg = "#c69026" }
"border"    = { fg = "#656c76" }
"selected"  = { bg = "#151b23", fg = "#d1d7e0", bold = true }

"source_marker" = { bg = "#39c5cf", fg = "#0d1117", bold = true }
"target_marker" = { bg = "#57ab5a", fg = "#0d1117", bold = true }

"status" = { bg = "#151b23" }
"status title" = { fg = "#0d1117", bg = "#539bf5", bold = true }

"revset title" = { fg = "#539bf5", bold = true }
"revset text" = { fg = "#d1d7e0", bold = true }
"revset completion text" = { fg = "#d1d7e0" }
"revset completion matched" = { fg = "#c69026", bold = true }
"revset completion dimmed" = { fg = "#656c76" }
"revset completion selected" = { bg = "#2f3742", fg = "#d1d7e0" }

"revisions" = { fg = "#d1d7e0" }
"revisions selected" = { bg = "#151b23"}
"revisions dimmed" = { fg = "#656c76" }
"revisions details selected" = { bg = "#2f3742" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#d1d7e0" }
"evolog selected" = { bg = "#2f3742", fg = "#d1d7e0", bold = true }

"menu" = { bg = "#0d1117" }
"menu title" = { fg = "#0d1117", bg = "#b083f0", bold = true }
"menu shortcut" = { fg = "#b083f0" }
"menu matched" = { fg = "#c69026", bold = true }
"menu dimmed" = { fg = "#656c76" }
"menu border" = { fg = "#151b23" }
"menu selected" = { bg = "#2f3742", fg = "#d1d7e0" }

"help" = { bg = "#0d1117" }
"help title" = { fg = "#57ab5a", bold = true, underline = true }
"help border" = { fg = "#151b23" }

"preview" = { fg = "#d1d7e0" }
"preview border" = { fg = "#151b23" }

"confirmation" = { bg = "#0d1117" }
"confirmation text" = { fg = "#539bf5", bold = true }
"confirmation dimmed" = { fg = "#656c76" }
"confirmation border" = { fg = "#f47067", bold = true }
"confirmation selected" = { bg = "#2f3742", fg = "#d1d7e0" }

"undo" = { bg = "#0d1117" }
"undo confirmation dimmed" = { fg = "#656c76" }
"undo confirmation selected" = { bg = "#2f3742", fg = "#d1d7e0" }

"success" = { fg = "#57ab5a", bold = true }
"error" = { fg = "#f47067", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#b083f0" }
"status dimmed" = { fg = "#656c76" }

"details" = { fg = "#d1d7e0" }
"details selected" = { bold = true }
"completion" = { fg = "#d1d7e0" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#539bf5" }
"branch" = { fg = "#f69d50" }
"commit" = { fg = "#57ab5a" }
"file" = { fg = "#c69026" }
"change" = { fg = "#f47067" }
"bookmark" = { fg = "#b083f0" }


