## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Github Light High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#454c54", bg = "#ffffff" }
"dimmed"    = { fg = "#818b98", bg = "#ffffff" }
"title"     = { fg = "#0349b4", bold = true }
"shortcut"  = { fg = "#622cbc" }
"matched"   = { fg = "#4e2c00" }
"border"    = { fg = "#818b98" }
"selected"  = { bg = "#f6f8fa", fg = "#454c54", bold = true }

"source_marker" = { bg = "#3192aa", fg = "#ffffff", bold = true }
"target_marker" = { bg = "#055d20", fg = "#ffffff", bold = true }

"status" = { bg = "#f6f8fa" }
"status title" = { fg = "#ffffff", bg = "#1168e3", bold = true }

"revset title" = { fg = "#0349b4", bg = "#f6f8fa", bold = true }
"revset text" = { fg = "#454c54", bold = true }
"revset completion text" = { fg = "#454c54" }
"revset completion matched" = { fg = "#4e2c00", bold = true }
"revset completion dimmed" = { fg = "#818b98" }
"revset completion selected" = { bg = "#25292e", fg = "#d1d9e0" }

"revisions" = { fg = "#454c54" }
"revisions selected" = { bg = "#d1d9e0"}
"revisions dimmed" = { fg = "#818b98" }
"revisions details selected" = { bg = "#59636e" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#454c54" }
"evolog selected" = { bg = "#25292e", fg = "#f6f8fa", bold = true }

"menu" = { bg = "#ffffff" }
"menu title" = { fg = "#ffffff", bg = "#844ae7", bold = true }
"menu shortcut" = { fg = "#844ae7" }
"menu matched" = { fg = "#4e2c00", bold = true }
"menu dimmed" = { fg = "#818b98" }
"menu border" = { fg = "#f6f8fa" }
"menu selected" = { bg = "#25292e", fg = "#f6f8fa" }

"help" = { bg = "#ffffff" }
"help title" = { fg = "#055d20", bold = true, underline = true }
"help border" = { fg = "#f6f8fa" }

"preview" = { fg = "#454c54" }
"preview border" = { fg = "#f6f8fa" }

"confirmation" = { bg = "#ffffff" }
"confirmation text" = { fg = "#0349b4", bold = true }
"confirmation dimmed" = { fg = "#818b98" }
"confirmation border" = { fg = "#86061d", bold = true }
"confirmation selected" = { bg = "#25292e", fg = "#f6f8fa" }

"undo" = { bg = "#ffffff" }
"undo confirmation dimmed" = { fg = "#818b98" }
"undo confirmation selected" = { bg = "#25292e", fg = "#f6f8fa" }

"success" = { fg = "#055d20", bold = true }
"error" = { fg = "#86061d", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#844ae7" }
"status dimmed" = { fg = "#818b98" }

"details" = { fg = "#454c54" }
"details selected" = { bold = true }
"completion" = { fg = "#454c54" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#1168e3" }
"branch" = { fg = "#3192aa" }
"commit" = { fg = "#055d20" }
"file" = { fg = "#4e2c00" }
"change" = { fg = "#86061d" }
"bookmark" = { fg = "#844ae7" }


