## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Lichen Chartreuse Dark
# Scheme author: Aaron Colichia (https://aaron.colichia.org/)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#e0e5da", bg = "#151613" }
"dimmed"    = { fg = "#899282", bg = "#151613" }
"title"     = { fg = "#78adc4", bold = true }
"shortcut"  = { fg = "#bfa6d4" }
"matched"   = { fg = "#b2d084" }
"border"    = { fg = "#899282" }
"selected"  = { bg = "#1c1e1a", fg = "#e0e5da", bold = true }

"source_marker" = { bg = "#9cc6c9", fg = "#151613", bold = true }
"target_marker" = { bg = "#83bda5", fg = "#151613", bold = true }

"status" = { bg = "#1c1e1a" }
"status title" = { fg = "#151613", bg = "#78adc4", bold = true }

"revset title" = { fg = "#78adc4", bold = true }
"revset text" = { fg = "#e0e5da", bold = true }
"revset completion text" = { fg = "#e0e5da" }
"revset completion matched" = { fg = "#b2d084", bold = true }
"revset completion dimmed" = { fg = "#899282" }
"revset completion selected" = { bg = "#3e5123", fg = "#e0e5da" }

"revisions" = { fg = "#e0e5da" }
"revisions selected" = { bg = "#1c1e1a"}
"revisions dimmed" = { fg = "#899282" }
"revisions details selected" = { bg = "#3e5123" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#e0e5da" }
"evolog selected" = { bg = "#3e5123", fg = "#e0e5da", bold = true }

"menu" = { bg = "#151613" }
"menu title" = { fg = "#151613", bg = "#bfa6d4", bold = true }
"menu shortcut" = { fg = "#bfa6d4" }
"menu matched" = { fg = "#b2d084", bold = true }
"menu dimmed" = { fg = "#899282" }
"menu border" = { fg = "#1c1e1a" }
"menu selected" = { bg = "#3e5123", fg = "#e0e5da" }

"help" = { bg = "#151613" }
"help title" = { fg = "#83bda5", bold = true, underline = true }
"help border" = { fg = "#1c1e1a" }

"preview" = { fg = "#e0e5da" }
"preview border" = { fg = "#1c1e1a" }

"confirmation" = { bg = "#151613" }
"confirmation text" = { fg = "#78adc4", bold = true }
"confirmation dimmed" = { fg = "#899282" }
"confirmation border" = { fg = "#e28b82", bold = true }
"confirmation selected" = { bg = "#3e5123", fg = "#e0e5da" }

"undo" = { bg = "#151613" }
"undo confirmation dimmed" = { fg = "#899282" }
"undo confirmation selected" = { bg = "#3e5123", fg = "#e0e5da" }

"success" = { fg = "#83bda5", bold = true }
"error" = { fg = "#e28b82", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#bfa6d4" }
"status dimmed" = { fg = "#899282" }

"details" = { fg = "#e0e5da" }
"details selected" = { bold = true }
"completion" = { fg = "#e0e5da" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#78adc4" }
"branch" = { fg = "#d5ad73" }
"commit" = { fg = "#83bda5" }
"file" = { fg = "#b2d084" }
"change" = { fg = "#e28b82" }
"bookmark" = { fg = "#bfa6d4" }


