## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Sequoia Moonlight Dark
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#868690", bg = "#0f1014" }
"dimmed"    = { fg = "#43444d", bg = "#0f1014" }
"title"     = { fg = "#c58fff", bold = true }
"shortcut"  = { fg = "#9898a6" }
"matched"   = { fg = "#9898a6" }
"border"    = { fg = "#43444d" }
"selected"  = { bg = "#111216", fg = "#868690", bold = true }

"source_marker" = { bg = "#ffbb88", fg = "#0f1014", bold = true }
"target_marker" = { bg = "#8eb6f5", fg = "#0f1014", bold = true }

"status" = { bg = "#111216" }
"status title" = { fg = "#0f1014", bg = "#c58fff", bold = true }

"revset title" = { fg = "#c58fff", bold = true }
"revset text" = { fg = "#868690", bold = true }
"revset completion text" = { fg = "#868690" }
"revset completion matched" = { fg = "#9898a6", bold = true }
"revset completion dimmed" = { fg = "#43444d" }
"revset completion selected" = { bg = "#111216", fg = "#868690" }

"revisions" = { fg = "#868690" }
"revisions selected" = { bg = "#111216"}
"revisions dimmed" = { fg = "#43444d" }
"revisions details selected" = { bg = "#111216" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#868690" }
"evolog selected" = { bg = "#111216", fg = "#868690", bold = true }

"menu" = { bg = "#0f1014" }
"menu title" = { fg = "#0f1014", bg = "#9898a6", bold = true }
"menu shortcut" = { fg = "#9898a6" }
"menu matched" = { fg = "#9898a6", bold = true }
"menu dimmed" = { fg = "#43444d" }
"menu border" = { fg = "#111216" }
"menu selected" = { bg = "#111216", fg = "#868690" }

"help" = { bg = "#0f1014" }
"help title" = { fg = "#8eb6f5", bold = true, underline = true }
"help border" = { fg = "#111216" }

"preview" = { fg = "#868690" }
"preview border" = { fg = "#111216" }

"confirmation" = { bg = "#0f1014" }
"confirmation text" = { fg = "#c58fff", bold = true }
"confirmation dimmed" = { fg = "#43444d" }
"confirmation border" = { fg = "#f58ee0", bold = true }
"confirmation selected" = { bg = "#111216", fg = "#868690" }

"undo" = { bg = "#0f1014" }
"undo confirmation dimmed" = { fg = "#43444d" }
"undo confirmation selected" = { bg = "#111216", fg = "#868690" }

"success" = { fg = "#8eb6f5", bold = true }
"error" = { fg = "#f58ee0", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#9898a6" }
"status dimmed" = { fg = "#43444d" }

"details" = { fg = "#868690" }
"details selected" = { bold = true }
"completion" = { fg = "#868690" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#c58fff" }
"branch" = { fg = "#f58ee0" }
"commit" = { fg = "#8eb6f5" }
"file" = { fg = "#9898a6" }
"change" = { fg = "#f58ee0" }
"bookmark" = { fg = "#9898a6" }


