## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Apprentice
# Scheme author: Romain Lafourcade (https://github.com/romainl)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#bcbcbc", bg = "#262626" }
"dimmed"    = { fg = "#444444", bg = "#262626" }
"title"     = { fg = "#5f87af", bold = true }
"shortcut"  = { fg = "#5f5f87" }
"matched"   = { fg = "#ffffaf" }
"border"    = { fg = "#444444" }
"selected"  = { bg = "#303030", fg = "#bcbcbc", bold = true }

"source_marker" = { bg = "#5fafaf", fg = "#262626", bold = true }
"target_marker" = { bg = "#87af87", fg = "#262626", bold = true }

"status" = { bg = "#303030" }
"status title" = { fg = "#262626", bg = "#87afd7", bold = true }

"revset title" = { fg = "#5f87af", bold = true }
"revset text" = { fg = "#bcbcbc", bold = true }
"revset completion text" = { fg = "#bcbcbc" }
"revset completion matched" = { fg = "#ffffaf", bold = true }
"revset completion dimmed" = { fg = "#444444" }
"revset completion selected" = { bg = "#3a3a3a", fg = "#bcbcbc" }

"revisions" = { fg = "#bcbcbc" }
"revisions selected" = { bg = "#303030"}
"revisions dimmed" = { fg = "#444444" }
"revisions details selected" = { bg = "#3a3a3a" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#bcbcbc" }
"evolog selected" = { bg = "#3a3a3a", fg = "#bcbcbc", bold = true }

"menu" = { bg = "#262626" }
"menu title" = { fg = "#262626", bg = "#8787af", bold = true }
"menu shortcut" = { fg = "#8787af" }
"menu matched" = { fg = "#ffffaf", bold = true }
"menu dimmed" = { fg = "#444444" }
"menu border" = { fg = "#303030" }
"menu selected" = { bg = "#3a3a3a", fg = "#bcbcbc" }

"help" = { bg = "#262626" }
"help title" = { fg = "#87af87", bold = true, underline = true }
"help border" = { fg = "#303030" }

"preview" = { fg = "#bcbcbc" }
"preview border" = { fg = "#303030" }

"confirmation" = { bg = "#262626" }
"confirmation text" = { fg = "#5f87af", bold = true }
"confirmation dimmed" = { fg = "#444444" }
"confirmation border" = { fg = "#ff8700", bold = true }
"confirmation selected" = { bg = "#3a3a3a", fg = "#bcbcbc" }

"undo" = { bg = "#262626" }
"undo confirmation dimmed" = { fg = "#444444" }
"undo confirmation selected" = { bg = "#3a3a3a", fg = "#bcbcbc" }

"success" = { fg = "#87af87", bold = true }
"error" = { fg = "#ff8700", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#8787af" }
"status dimmed" = { fg = "#444444" }

"details" = { fg = "#bcbcbc" }
"details selected" = { bold = true }
"completion" = { fg = "#bcbcbc" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#87afd7" }
"branch" = { fg = "#5fafaf" }
"commit" = { fg = "#87af87" }
"file" = { fg = "#ffffaf" }
"change" = { fg = "#ff8700" }
"bookmark" = { fg = "#8787af" }


